import org.jetbrains.intellij.platform.gradle.TestFrameworkType

plugins {
    id("org.jetbrains.kotlin.jvm")
    id("org.jetbrains.intellij.platform")
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("org.commonmark:commonmark:0.22.0")

    testImplementation("junit:junit:4.13.2")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")

    intellijPlatform {
        intellijIdea("2025.2.6.1")
        testFramework(TestFrameworkType.Platform)
    }
}

intellijPlatform {
    pluginConfiguration {
        description =
            "Scopecreep — software-defined hardware control inside JetBrains IDEs. " +
                "Drives real lab instruments (PSU, oscilloscope) through a managed Python sidecar."
    }
}

// -------------------------------------------------------------------------
// Bundle the jbhack Python agent backend (python/{api,agent,drivers,schdoc})
// into plugin resources under /sidecar/benchy/. Emits a manifest so the
// runtime SidecarManager can enumerate + extract entries without scanning
// the JAR. Source path defaults to ../python and is overridable via the
// gradle property `benchy.backend.path`.
// -------------------------------------------------------------------------
val benchyBackendSrc: String =
    (project.findProperty("benchy.backend.path") as String?) ?: "../python"

val bundleBenchyBackend = tasks.register("bundleBenchyBackend") {
    group = "build"
    description = "Copy jbhack agent backend into resources/sidecar/benchy/ + manifest."

    val srcDir = file(benchyBackendSrc)
    val outDir = layout.buildDirectory.dir("generated/benchy-resources/sidecar/benchy").get().asFile
    if (srcDir.exists()) {
        inputs.dir(srcDir).withPathSensitivity(org.gradle.api.tasks.PathSensitivity.RELATIVE)
    }
    outputs.dir(layout.buildDirectory.dir("generated/benchy-resources/sidecar/benchy"))

    doLast {
        outDir.deleteRecursively()
        outDir.mkdirs()

        if (!srcDir.exists()) {
            logger.warn("bundleBenchyBackend: source $srcDir not found — emitting empty bundle.")
            outDir.resolve("benchy-manifest.txt").writeText("")
            outDir.resolve("agent_worker.py").writeText(
                "# Placeholder — benchy backend was not bundled at build time.\n" +
                    "raise SystemExit('benchy backend not bundled; set -Pbenchy.backend.path=/abs/to/python')\n"
            )
            return@doLast
        }

        val includes = listOf("api", "agent", "drivers", "schdoc")
        val manifest = mutableListOf<String>()

        includes.forEach { pkg ->
            val pkgDir = srcDir.resolve(pkg)
            if (!pkgDir.exists()) {
                logger.warn("bundleBenchyBackend: missing package $pkgDir — skipping.")
                return@forEach
            }
            pkgDir.walkTopDown().filter { it.isFile }.forEach { f ->
                val rel = srcDir.toPath().relativize(f.toPath()).toString().replace('\\', '/')
                if (rel.contains("__pycache__") ||
                    rel.contains("/tests/") ||
                    rel.endsWith(".pyc") ||
                    rel.endsWith(".pyo")
                ) return@forEach
                val dst = outDir.toPath().resolve(rel).toFile()
                dst.parentFile.mkdirs()
                f.copyTo(dst, overwrite = true)
                manifest.add(rel)
            }
        }

        val shim = """
            |# Generated by Scopecreep bundleBenchyBackend.
            |# Re-exports the jbhack FastAPI app so `uvicorn agent_worker:app` works
            |# when launched with cwd = this directory.
            |from api.server import app  # noqa: F401
            |
            |if __name__ == "__main__":
            |    import uvicorn
            |    uvicorn.run(app, host="0.0.0.0", port=8000)
            |""".trimMargin()
        outDir.resolve("agent_worker.py").writeText(shim)
        manifest.add("agent_worker.py")

        outDir.resolve("benchy-manifest.txt").writeText(manifest.sorted().joinToString("\n"))
        logger.lifecycle("bundleBenchyBackend: bundled ${manifest.size} files from $srcDir")
    }
}

sourceSets.named("main") {
    resources.srcDir(layout.buildDirectory.dir("generated/benchy-resources"))
}

tasks.named("processResources") {
    dependsOn(bundleBenchyBackend)
}
